language: ruby
rvm:
- 2.6.5

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/run_jekyll.sh
script: ./script/validate_json.rb
script: ./script/ping_websites.rb
script: ./script/check_files_formatting.sh

sudo: false
