language: ruby
rvm:
- 2.6.5

jobs:
  include:
    - stage: Install Dependencies
      script:
        - gem install bundler
        - bundle install --jobs 3 --retry 3
    - stage: run jekyll
      script: ./script/run_jekyll.sh
    - stage: validate json
      script: ./script/validate_json.rb
    - stage: ping websites
      script: ./script/ping_websites.rb
    - stage: check files formatting
      script: ./script/check_files_formatting.sh

sudo: false
