language: ruby
rvm:
- 2.6.5

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.

jobs:
  include:
    - stage: run jekyll
      script: ./script/run_jekyll.sh
    - stage: validate json
      script: ./script/validate_json.rb
    - stage: ping websites
      script: ./script/ping_websites.rb
    - stage: check files formatting
      script: ./script/check_files_formatting.sh

sudo: false
