name: Validate Commit
on: [push, pull_request]
jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Jekyll
        run: script/run_jekyll.sh
      - name: Validate JSON
        run: script/validate_json.rb
      - name: Ping Websites
        run: script/ping_websites.rb
      - name: Check Files Formatting
        run: script/check_files_formatting.sh
